services:
  - type: web
    name: social-media-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 1 web_server:app
    envVars:
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: LINKEDIN_ACCESS_TOKEN
        sync: false
      - key: LINKEDIN_PERSON_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
